name: Test Matrix

on:
  push:
    branches: [test-matrix]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
          - os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check
        run: echo "Runner: ${{ matrix.os }}"
